version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=restaurant
      - POSTGRES_PASSWORD=restaurant123
      - POSTGRES_DB=restaurant_db
    volumes:
      - /Users/anthony/Documents/Personal/ai-test/data/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7.4.3
    ports:
      - "6379:6379"
    volumes:
      - /Users/anthony/Documents/Personal/ai-test/data/redis/:/data
    restart: unless-stopped

volumes:
  postgres_data: 
  redis_data: